#1 Calculation of Fibonacci
asusikov/go-core pull request #1
Opened 2020-10-14 16:41 UTC by asusikov

### What does this PR do?

* add package with function what calculate fibonacci number
* add util to get number from user via command line argument

2020-10-14 19:31 UTC, DmitriyVTitov requested changes
вы посчитали факториал (дважды), а нужно числа Фибоначчи (один раз)

2020-10-14 19:31 UTC, DmitriyVTitov commented on math/cmd/factorial/main.go
> +	"go-core.course/math/pkg/factorial"
факториал - это немного другое

2020-10-14 19:31 UTC, DmitriyVTitov commented on math/cmd/factorial/main.go
> +  return *inputNumber
всё это можно поместить в main()

2020-10-14 19:31 UTC, DmitriyVTitov commented on math/cmd/factorial/main.go
> +		fmt.Println(err)
тут лучше := вместо var

2020-10-14 19:31 UTC, DmitriyVTitov commented on math/cmd/factorial/main.go
> +  return *inputNumber
странное форматирование кода. IDE должна применять gofmt автоматически

2020-10-14 19:31 UTC, DmitriyVTitov commented on math/cmd/fibonacci/main.go
> +	"go-core.course/math/pkg/fibonacci"
а, вот это похоже

2020-10-14 19:31 UTC, DmitriyVTitov commented on math/pkg/fibonacci/fibonacci.go
> +	return number * nextResult
это опять похоже на факториал, а не Фибоначчи

2020-10-14 19:39 UTC, asusikov commented
Да, я понял что не то сделал после того как отправил PR на проверку и решил посмотреть решение других студентов. А дубль потому, что решил оставить факториал.

2020-10-14 19:42 UTC, asusikov commented on math/cmd/factorial/main.go
> +  return *inputNumber
Но можно и оставить в отдельной функции?🙂

2020-10-14 19:50 UTC, DmitriyVTitov commented on math/cmd/factorial/main.go
> +  return *inputNumber
нет, и вот почему: программа должна быть написана так, чтобы читать её сверху вниз, с минимальными переходами.
вы добавляете один переход туда-сюда без какой-либо выгоды.

2020-10-15 05:33 UTC, asusikov commented on math/cmd/factorial/main.go
> +  return *inputNumber
Готов поспорить :) Выгода в том, что мы несколько конструкций объединяем и даем им описание, что они делают - имя функции. Соответственно при чтении меньше когнитивная нагрузка - проще прочитать название функции и понять что она делает, читать прочитать несколько строчек кода и делать уже вывод о том, что они делают. Также функции помогают нам ограничивать контексты - с помощью их мы готовим некоторое API с маленькими шагами, и потом их объединяем. Насчет перехода - при чтении мы сразу понимаем что происходит исходя из наименования и можем понять надо ли нам переходить в нее или нет - в зависимости от требуемой задачи - если надо поправить/добавить парсинг входных параметров - идем вглубь, нет - пропускаем и читаем дальше.
P.S.: Да, возможно данный пример не самый лучший и выше названные преимущества не так ярко проявляются, но больших объемах работает отлично и надеюсь, смог убедить, что стоит оставить и данном случае тоже

2020-10-16 11:23 UTC, DmitriyVTitov approved these changes
1. Про факториал - лишнее.
2. Вместо получения одного числа простой функцией вы выдаёте массив, используя три функции.
3. Вместо одного простого теста - три не очень понятных.

Не переусложняйте код, не решайте задач, которые не поставлены и проблем которых ещё нет.
Для первого задания посчитаем выполненным. Далее я надеюсь на более простые решения. :)

2020-10-16 11:23 UTC, DmitriyVTitov commented on math/cmd/factorial/main.go
> +package main
этого же не было в задании
пожалуйста, не усложняйте и так весьма трудоёмкий процесс проверки ДЗ

2020-10-16 11:23 UTC, DmitriyVTitov commented on math/cmd/fibonacci/main.go
> +func parseInputNumber() (int, error) {
я прочитал ваш аргумент, в нём есть резон, конечно
но в Go принято писать более топорно. этой функцией, на мой взгляд, вы решаете несуществующую проблему и усложняете мне понимание кода.
впрочем, повторюсь, ваш аргумент понятен

2020-10-16 11:23 UTC, DmitriyVTitov commented on math/cmd/fibonacci/main.go
> +	inputNumber, err := parseInputNumber()
тогда уж передавали бы аргумент в функцию (максимальный номер числа) и избавились от глобальной переменной

2020-10-16 11:23 UTC, DmitriyVTitov commented on math/pkg/fibonacci/fibonacci.go
> +const secondFibonacciElement = 1
глобальную область видимости лучше оставить чистой

2020-10-16 11:23 UTC, DmitriyVTitov commented on math/pkg/fibonacci/fibonacci.go
> +}
нужно по номеру получить число Фибоначчи - это одна функция, в ней две переменных, возвращает одно целое число.

2020-10-16 11:23 UTC, DmitriyVTitov commented on math/pkg/fibonacci/fibonacci_test.go
> +}
одна функция для получения числа Фибоначчи по его номеру - один тест

2020-10-16 15:09 UTC, asusikov commented on math/cmd/factorial/main.go
> +package main
Это решил оставить, так как уже было сделано и требовалось только переименовать. Считаю, что когда учишься любая лишняя строчка кода это хорошо. Но! Я не учел трудозатраты на ревью. В будущем, буду решать только поставленные задания

2020-10-16 15:10 UTC, asusikov commented on math/cmd/fibonacci/main.go
> +func parseInputNumber() (int, error) {
Я учту ваше замечание в будущем

2020-10-16 15:10 UTC, asusikov commented on math/pkg/fibonacci/fibonacci.go
> +const secondFibonacciElement = 1
А разве константы с маленькой буквы попадут в глобальную видимость?

2020-10-16 15:11 UTC, asusikov commented on math/pkg/fibonacci/fibonacci.go
> +}
БЛин, я опять не так понял задание?! 😳

2020-10-16 15:12 UTC, asusikov commented on math/pkg/fibonacci/fibonacci_test.go
> +}
Я задавался этим вопрос(писал об этом в отчете) - кода надо проверить несколько кейсов надо все в одном тесте тоже проверять? Этот вариант сделал по аналогии, как я делаю обычно - один кейс - один тест

2020-10-16 15:49 UTC, DmitriyVTitov commented on math/pkg/fibonacci/fibonacci.go
> +const secondFibonacciElement = 1
ну так они же доступны у вас в любой функции - это и есть глобальная область видимости (она же область видимости всего пакета)
в других файлах этого же пакета (каталога) тоже будут доступны в любой функции

2020-10-16 15:50 UTC, DmitriyVTitov commented on math/pkg/fibonacci/fibonacci_test.go
> +}
одна функция - один тест. в Го часто используют табличные тесты, в которых в таблице полно случаев.
потом в цикле запускают подтесты - будет отдельное занятие по тестированию

2020-10-16 16:10 UTC, merged