[WIP] #3 Scanner
asusikov/go-core pull request #3
Opened 2020-10-22 08:46 UTC by asusikov

### What does this PR do?

* added new interface to scan site
* added scanner as dependency to engin

2020-10-31 13:16 UTC, DmitriyVTitov requested changes
Я не понимаю, что вы прислали.
Сделайте отдельный каталог для решения ДЗ по каждому уроку и пришлите полностью зелёный PR. Я не могу разбираться в истории изменений.

2020-10-31 13:23 UTC, asusikov commented
Я прислал изменения, которые я сделал чтобы решить домашнее задание №3. Вроде требований к сдаче про новый каталог не было. Было только про отдельный PR на каждое домашнее задание. Если надо отдельные каталоги, то пожалуйста добавьте эти требования и опишите, как это должно быть. Я вот например не понимаю как сдавать изменения в отдельном каталоге - там должны содержаться файлы, которые я изменил или полностью должен скопирован проект, либо как еще.

2020-10-31 13:30 UTC, DmitriyVTitov commented
> Я прислал изменения, которые я сделал чтобы решить домашнее задание №3. Вроде требований к сдаче про новый каталог не было. Было только про отдельный PR на каждое домашнее задание. Если надо отдельные каталоги, то пожалуйста добавьте эти требования и опишите, как это должно быть. Я вот например не понимаю как сдавать изменения в отдельном каталоге - там должны содержаться файлы, которые я изменил или полностью должен скопирован проект, либо как еще.

Лучше полностью скопировать. Как с чистого листа.
Историю изменений очень трудно смотреть, присылайте полностью зелёный PR. Новое задание - новый каталог.

2020-10-31 13:33 UTC, asusikov commented
Хм... Полностью не согласен - так придется смотреть код, который не менялся и понять что было сделано по заданию сложно понять. Но раз такие требование, то буду делать. P.S.: добавьте это требования куда-либо, чтобы все знали об этом

2020-11-02 14:15 UTC, DmitriyVTitov approved these changes
Старайтесь делать код максимально простым.

2020-11-02 14:15 UTC, DmitriyVTitov commented on review/cmd/cli/main.go
> +	flag.Parse()
можно все флажки убрать, их уже давно нет в задании.
упрощайте код максимально. это основной показатель качества.

2020-11-02 14:15 UTC, DmitriyVTitov commented on review/cmd/cli/main.go
> +	runSearch := false
какие-то глобальные переменные с непонятными именами и без комментариев

2020-11-02 14:15 UTC, DmitriyVTitov commented on review/cmd/cli/main.go
> +		runLoop = isInteractive && !runSearch
что-то сложное, непонятное
упрощайте, избавляйтесь от всего этого

2020-11-02 14:15 UTC, DmitriyVTitov commented on review/pkg/engine/engine_test.go
> +}
имитация пакета робота не должна быть реализована в пакете `engine`
каждый пакет должен заниматься своим делом

2020-11-03 07:08 UTC, asusikov commented on review/cmd/cli/main.go
> +	flag.Parse()
Я использовал код, который я писал ранее - там эти флажки были, дополнительного хадания чтобы удалить их не было, поэтому они здесь и появились

2020-11-03 07:10 UTC, asusikov commented on review/pkg/engine/engine_test.go
> +}
Почему? Мок интерфейса должен находится там же где и объявление интерфейса - интерфейс лежит в engine, поэтому я туда же положил мок

2020-11-03 11:09 UTC, DmitriyVTitov commented on review/pkg/engine/engine_test.go
> +}
> Мок интерфейса должен находится там же где и объявление интерфейса - интерфейс лежит в engine, поэтому я туда же положил мок

Вы можете самостоятельно придумывать правила и писать код в соответствии с ними. А можете работать по готовым правилам.
Первый вариант не эффективный.

2020-11-03 11:17 UTC, asusikov commented on review/pkg/engine/engine_test.go
> +}
Я не придумываю правила, а использую уже готовые. Можете привести объективные доводы, почему он не эффективен?

2020-11-05 09:12 UTC, merged